### PR TITLE
Compiler warnings

### PR DESCRIPTION
**Pull request by KurtE**
This removes some, but not all of the compiler warnings when I am working with a Teensy.

Still debugging so will let you know 

This is from the issue #3

### CODE REVIEW

**Comment by RB-ENantel** [comment]
Would be ready to do the merge, can you take a look at those:
- Remove the files associated to "LSS_Query" from the PR & undo the changes to the example.
- Add the new "architectures" in the [library.property](https://github.com/Lynxmotion/LSS_Library_Arduino/blob/master/library.properties) & update the version to 1.4.0.

**Comment by KurtE** [comment]
Sorry about the extra build system files - I build using sublime text projects which makes it nice.
I also undid most of the change to the example sketch.
So it has:
```
#define LSS_ID    (0)
#define LSS_BAUD  (LSS_DefaultBaud)
#define LSS_SERIAL  (Serial)

// Create one LSS object
LSS myLSS = LSS(LSS_ID);

void setup()
{
  // Initialize the LSS bus
  LSS::initBus(LSS_SERIAL, LSS_BAUD);
}
```
Which will not build on the Teensy as Serial is not a HardwareSerial class.

Maybe better would be to change: 

    #define LSS_SERIAL  (Serial)

To something like:

   #define LSS_SERIAL (LSS_DefaultSerial)

And in the library header file 

Have something in it like:
```
#if defined(__AVR__) 
#define LSS_DefaultSerial Serial
#else
#define LSS_DefaultSerial Serial1
#endif
```
Or maybe More resolution on AVR to do like other libraries:
Where UnO (ATMEGA328) and the like user Serial... 
Not sure how complete ... 

As for library properties don't need to change.

As for Library version, I think that is something owner of library has to do.

**Comment by Ragnarok700** [comment]
@KurtE what about adding "teensy" to the architectures?

**Comment by KurtE** [comment]
I assume you are talking about:
```
name=Lynxmotion Smart Servo -LSS-
version=1.3.1
author=Sebastien Parent-Charette <support@robotshop.com>
maintainer=Sebastien Parent-Charette <support@robotshop.com>
sentence=A library that makes using the LSS simple.
paragraph=Offers support for Arduino Uno, Mega and others through the use of the Stream class for serial communication.
category=Device Control
url=https://www.robotshop.com/info/wiki/lynxmotion/view/lynxmotion-smart-servo/
architectures=avr
includes=LSS.h
```
For reasons one can agree or disagree with, Paul of PRJC long ago decided to put everything under AVR

So for example: on my machine the Teensy stuff is at:
c:\arduino-1.8.13\hardware\teensy\avr\...
So the avr already in your architectures matches.

I believe one of the main reasons for this is he did not want to have to put up multiple copies of the same library. 
For example the Servos library works with both real avr (such as Teensy 2.x) in the above mentioned directory
is cores\teensy - for the AVR based teensy boards which still ship.
cores\teensy3 - Is the Teensy3.x as well as the Teensy LC code 
cores\teensy4 - is the Teensy 4.x

Again depending on if the desire is to go to LSS_DefaultSerial
Yes all of the examples should be updated.

**Comment by Ragnarok700** [comment]
@KurtE Thanks for the details concerning architectures for teensy/avr. I was not aware!

As for the examples, I made a [PR](https://github.com/Lynxmotion/LSS_Library_Arduino/pull/5) for that update. Should be compatible with this one here.

**Pull request merged**
